# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
# Problem that is caused by the name of file "deploy.yaml" as we can see here https://github.com/redhat-developer/vscode-yaml/issues/397
namespace: sandbox
image: techtrends:latest
name: techtrends
replicas: 1
resources:
  requests: CPU 250m and memory 64Mi
  limits: CPU 500m and memory 128Mi
container port: 3111
liveness probe:
  path: /healthz
  port: 3111
readiness probe:
  path: /healthz
  port: 3111