kind: Deployment
apiVersion: apps/v1
metadata:
  name: techtrends
  labels:
    app: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
       containers:
        - image: duarch/techtrends:latest
        name: techtrends
        ports:
          - containerPort:  3111
            protocol: TCP
        resources:
          requests:
            memory: 64mi
            cpu: 250m
          limits:
            memory: 128mi
            cpu: 500m
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111